version: '3.3'

services:
    nginx:
        image: nginx:1.16.1
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./Nginx/core:/etc/nginx/conf.d
            - ./Nginx/www/:/var/www/
            - ./Nginx/Logs:/var/log/nginx/
            - ./Nginx/html:/usr/share/nginx/html/
        links:
            - php

    mysql:
        image: mysql:latest
        ports:
            - "3306:3306"
        container_name: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=mypassword
            - MYSQL_DATABASE=php_app
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - DB_HOST=db


        volumes:
            - ./MySQL:/var/lib/mysql


    php:
        build: ./PHP
        container_name: php-fpm
        volumes:
            - ./Nginx/www/:/var/www/
        links:
            - mysql


    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - 8090:80
        links:
            - mysql:db